# Generated by Django 5.2.1 on 2026-01-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=20, null=True)),
                ('contactmethod', models.CharField(max_length=20)),
                ('visitingfirsttime', models.CharField(max_length=10)),
                ('hearaboutus', models.CharField(max_length=30)),
                ('hearaboutother', models.CharField(blank=True, max_length=60, null=True)),
                ('attendanotherchurch', models.CharField(max_length=10)),
                ('ifyeschurchname', models.CharField(blank=True, max_length=100, null=True)),
                ('areasforprayer', models.CharField(max_length=50)),
                ('areaother', models.CharField(blank=True, max_length=50, null=True)),
                ('prayerwithsomeone', models.CharField(max_length=10)),
                ('contactfrompastor', models.CharField(max_length=10)),
                ('prayerrequestmessage', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
