# Generated by Django 5.2.1 on 2026-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prayerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
