# Generated by Django 5.2.1 on 2026-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meetingrequest_meetingattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
