# Generated by Django 5.2.1 on 2026-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meetingrequest_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
